#!/usr/bin/env bash
# Bring up the DeployX local end-to-end stack via docker-compose.local.yml.
#
# - Generates a fresh .env.local with random ENCRYPTION_KEY + JWT_SECRET.
# - Creates the external proxy-network if missing.
# - Builds + starts the api + dashboard + traefik + docker-proxy services.
# - Waits up to 120s for the dashboard (via Traefik on :80) and api /healthz
#   (via docker compose exec) to come up before returning.
#
# Usage: scripts/up-local.sh
# Pair with scripts/down-local.sh to tear everything back down.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

ENV_FILE="$REPO_ROOT/.env.local"
COMPOSE_FILE="$REPO_ROOT/docker-compose.local.yml"

echo "[up-local] repo root: $REPO_ROOT"

if ! command -v docker >/dev/null 2>&1; then
  echo "[up-local] error: docker not on PATH" >&2
  exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "[up-local] error: docker compose plugin not available" >&2
  exit 1
fi
if ! command -v openssl >/dev/null 2>&1; then
  echo "[up-local] error: openssl not on PATH (needed for secret generation)" >&2
  exit 1
fi
if ! command -v curl >/dev/null 2>&1; then
  echo "[up-local] error: curl not on PATH (needed for health probing)" >&2
  exit 1
fi

# Always regenerate .env.local — fresh secrets per stack so we never accidentally
# carry an old encryption key across a `down -v` (which would corrupt env-var
# decryption against newly-encrypted rows). Test runs are stateless.
ENCRYPTION_KEY="$(openssl rand -hex 32)"
JWT_SECRET="$(openssl rand -hex 32)"

cat >"$ENV_FILE" <<EOF
# Generated by scripts/up-local.sh — DO NOT COMMIT.
PLATFORM_DOMAIN=localhost
ENCRYPTION_KEY=$ENCRYPTION_KEY
JWT_SECRET=$JWT_SECRET
EOF
chmod 600 "$ENV_FILE"
echo "[up-local] wrote fresh .env.local (secrets regenerated)"

# Traefik attaches to an external network so user-deployed projects can join it
# too. Idempotent: skip if it already exists.
if ! docker network inspect proxy-network >/dev/null 2>&1; then
  docker network create proxy-network >/dev/null
  echo "[up-local] created docker network proxy-network"
else
  echo "[up-local] docker network proxy-network already exists"
fi

echo "[up-local] building + starting services…"
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d --build

# --- Wait for the dashboard to be reachable through Traefik ---
DASHBOARD_URL="http://localhost/"
echo "[up-local] waiting for dashboard at $DASHBOARD_URL (up to 120s)…"
ready=0
for i in $(seq 1 60); do
  # Accept any non-5xx as "Traefik is routing"; the dashboard's SvelteKit
  # adapter-node returns 200 for / once it has bound.
  code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 3 "$DASHBOARD_URL" || echo 000)"
  if [[ "$code" =~ ^2|^3 ]]; then
    ready=1
    echo "[up-local] dashboard ready (HTTP $code) after ${i}x2s"
    break
  fi
  sleep 2
done

if [[ "$ready" -ne 1 ]]; then
  echo "[up-local] dashboard did not become ready in 120s. Recent logs:" >&2
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" logs --tail 100 traefik dashboard api || true
  exit 1
fi

# --- Wait for the api /healthz to return 200. The api isn't exposed on a host
#     port, so we probe it from inside the api container itself. ---
echo "[up-local] waiting for api /healthz…"
api_ready=0
for i in $(seq 1 60); do
  if docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" exec -T api \
      node -e "fetch('http://127.0.0.1:3001/healthz').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))" \
      >/dev/null 2>&1; then
    api_ready=1
    echo "[up-local] api /healthz responding after ${i}x2s"
    break
  fi
  sleep 2
done

if [[ "$api_ready" -ne 1 ]]; then
  echo "[up-local] api did not become ready in 120s. Recent logs:" >&2
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" logs --tail 100 api || true
  exit 1
fi

cat <<EOF

[up-local] Stack ready.
  Dashboard:        http://localhost/
  Traefik routing:  http://localhost/api/v1/...
  Traefik UI:       http://localhost:8080/
  Env file:         $ENV_FILE
  Compose file:     $COMPOSE_FILE

To tear down:
  scripts/down-local.sh
EOF
